spring:
  application:
    name: openmu-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/openmu
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath:sql/cms-schema.sql

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

admin:
  panel:
    username: admin
    password: openmu
    url: http://192.168.1.200:81

server:
  port: 8085