services:
  nginx-80:
    image: nginx:alpine
    container_name: nginx-web-80
    ports:
      - "80:80"
    restart: "unless-stopped"
    volumes:
      - ./nginx.prod80.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro

# We add another nginx here, just for HTTPs.
# The reason is, that it's not starting when we combine port 80 and 443 until
# the certificates are created.
# So, when running the certbot the first time, we need to be able to access
# the port 80 - and we solve this by separating the server configs.
  nginx-443:
    container_name: nginx-web-443
    build:
      dockerfile: Dockerfile
      context: ../../client
    ports:
      - "443:443"
    volumes:
      - ./nginx.prod443.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  cms-api:
    container_name: cms-api
    build:
      dockerfile: Dockerfile
      context: ../../server
    environment:
      DB_HOST: 192.168.1.200
      DB_PORT: 5432
      DB_NAME: openmu
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      ADMIN_PANEL_HOST: 192.168.1.200
      ADMIN_PANEL_PORT: 81
      ADMIN_PANEL_USERNAME: admin
      ADMIN_PANEL_PASSWORD: openmu
    restart: "unless-stopped"
    ports:
      - "8085"