events {
}

http {
    server {
        listen 80;
        listen [::]:80;

        server_name mu-michi.sytes.net www.mu-michi.sytes.net api.mu-michi.sytes.net admin.mu-michi.sytes.net;
        server_tokens off;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }
}